<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "football_manager"
 *
 * Auto generated by Extension Builder 2013-10-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Football Manager',
	'description' => 'This extension manages the schedule for the Ate Chay United football team.',
	'category' => 'plugin',
	'author' => 'Visay Keo',
	'author_email' => 'keo@visay.info',
	'author_company' => 'Visay.Info',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1-dev',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>